config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "artists#index"
  resources :artists do
    resources :songs, only: [:new, :create]
  end

  resources :songs, only: [:show]
  resources :playlists, only: [:index, :new, :create, :show, :edit, :update]
  get '/auth/spotify/callback', to: 'sessions#create'
  delete '/logout', to: 'session#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :image_path, presence: true

  has_many :songs
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  validates :name, presence: true
  
  has_many :playlist_songs
  has_many :songs, through: :playlist_songs
end

app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  belongs_to :song
  belongs_to :playlist
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
end

app/models/user.rb
class User < ApplicationRecord
  def self.find_or_create_from_auth(auth)
    User.find_or_create_by(
    provider: auth["provider"],
    uid: auth["info"]["id"],
    name: auth["info"]["display_name"]
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.create(artist_params)
    if @artist.save
      redirect_to @artist
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @artist.update(artist_params)
      redirect_to @artist
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  private

    def set_artist
      @artist = Artist.find(params[:id])
    end

    def artist_params
      params.require(:artist).permit(:name, :image_path)
    end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
    before_action :set_playlist, only: [:show, :edit, :update,]

  def index
    @playlists = Playlist.all
  end

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.create(playlist_params)
    if @playlist.save
      redirect_to @playlist
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @playlist.update(playlist_params)
      redirect_to @playlist
    else
      render :edit
    end
  end

  private

  def set_playlist
    @playlist = Playlist.find(params[:id])
  end

  def playlist_params
    params.require(:playlist).permit(:name, song_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_from_auth(request.env['omniauth.auth'])
    if @user
      session[:user_id] = @user.id
      redirect_to playlists_path
    end
  end

  def destroy
    session.clear
    redirect_to playlists_path
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def new
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.new
  end

  def create
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.create(song_params)

    redirect_to song_path(@song)
  end

  def show
    @song = Song.find(params[:id])
  end

  private

    def song_params
      params.require(:song).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>
<%= render partial: "shared/artist_form" %>

app/views/artists/index.html.erb
<h1>All Artists</h1>
<br>
<%= link_to "New Artist", new_artist_path %>
<br>
<ul>
  <%= render partial: "shared/index", locals: { target: @artists } %>
</ul>

app/views/artists/new.html.erb
<h1>New Artist</h1>
<%= render partial: "shared/artist_form" %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
<%= image_tag @artist.image_path %>
<br>
<%= link_to "Edit this Artist", edit_artist_path(@artist) %>
<%= link_to "Delete this Artist", artist_path(@artist), method: :delete %>
<%= link_to "New Song", new_artist_song_path(@artist) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MixMaster</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if current_user %>
      <h3>Welcome, <%= current_user.name %></h3>
      <%= link_to "Sign out", logout_path, method: :delete %>
    <% else %>
      <%= link_to "Sign in with Spotify", "/auth/spotify" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/playlists/edit.html.erb
<h1>Edit Playlist</h1>
<%= render partial: "shared/playlist_form" %>

app/views/playlists/index.html.erb
<h1>All Playlists</h1>
<%= link_to "New Playlist", new_playlist_path %>
<br>
<ul>
<%= render partial: "shared/index", locals: { target: @playlists } %>
</ul>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>
<%= render partial: "shared/playlist_form" %>

app/views/playlists/show.html.erb
<h1><%= @playlist.name %></h1>

<ul>
  <% @playlist.songs.each do |song| %>
    <li><%= link_to song.title, song %></li>
  <% end %>
</ul>
<%= link_to "Edit Playlist", edit_playlist_path(@playlist) %>

app/views/shared/_artist_form.erb
<%= form_for(@artist) do |f| %>
<%= render partial: "shared/errors", locals: { target: @artist } %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image_path %>
  <%= f.text_field :image_path %>

  <%= f.submit %>
<% end %>

app/views/shared/_errors.erb
<% if target.errors.any? %>
  <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% target.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

app/views/shared/_index.erb
<% target.each do |t| %>
  <li><%= link_to t.name, t %></li>
<% end %>

app/views/shared/_playlist_form.erb
<%= form_for(@playlist) do |f| %>
<%= render partial: "shared/errors", locals: { target: @playlist } %>
  <%= f.text_field :name %>

  <% Song.all.each do |song| -%>
    <div>
      <%= check_box_tag :song_ids, song.id, @playlist.songs.include?(song), :name => 'playlist[song_ids][]', id: "song-#{song.id}" %>
      <%= song.title %>
    </div>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/songs/new.html.erb
<h1>New Song</h1>
<p> Add a new song for <%= @artist.name %></p>
<%= form_for([@artist, @song]) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit %>
<% end %>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>
<%= link_to @song.artist.name, artist_path(@song.artist) %>